// <auto-generated />
namespace Telefon_Rehberi.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class tablo_güncellemesi : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(tablo_güncellemesi));
        
        string IMigrationMetadata.Id
        {
            get { return "202309232150597_tablo_güncellemesi"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
